[build-system]
build-backend = 'mesonpy'
backend-path = ['.']
requires = [
  'meson>=0.60.0',
  'ninja',
  'wheel',
  'pep621 >= 0.4.0',
  'tomli>=1.0.0',
  'typing-extensions>=3.7.4; python_version<"3.8"',
]

[project]
name = 'meson-python'
version = '0.4.0'
description = 'Meson Python build backend (PEP 517)'
readme = 'README.md'
requires-python = '>=3.7'
license = { file = 'LICENSE' }
keywords = ['meson', 'build', 'backend', 'pep517', 'package']
authors = [
  { name = 'Filipe Laíns', email = 'lains@riseup.net' },
]
classifiers = [
  'Development Status :: 4 - Beta',
  'Programming Language :: Python',
]

dependencies = [
  'colorama; os_name == "nt"',
  'meson>=0.60.0',
  'ninja >= 1.10.0',
  'pep621 >= 0.4.0',
  'patchelf-wrapper; sys_platform == "linux"',  # FIXME: broken package, see gh-52
  'wheel >= 0.36.0',
  'tomli>=1.0.0',
  'typing-extensions>=3.7.4; python_version<"3.8"',
]

[project.optional-dependencies]
test = [
  'pytest',
  'pytest-cov',
  'pytest-mock',
  'GitPython',
  'auditwheel',  # unused as of now
]
docs = [
  'furo>=2021.08.31',
  'sphinx~=4.0',
  'sphinx-autodoc-typehints>=1.10',
]

[project.urls]
homepage = 'https://github.com/FFY00/mesonpy'
repository = 'https://github.com/FFY00/mesonpy'
documentation = 'https://mesonpy.readthedocs.io'
changelog = 'https://mesonpy.readthedocs.io/en/latest/changelog.html'
